secretGenerator:
  - name: mongo-db-secret
    literals:
    - database=kube_db
    - rootuser=root
    - rootpassword=passwort
    - user=usertest
    - password=pwdtest
  - name: mongo-express-secret
    literals:
    - adminusername=dev
    - adminpassword=dev
namespace: app
resources:
  - namespace.yaml
  - mongo-deployment.yaml
 # - kube-server-deployment.yaml
 # - kube-client-deployment.yaml  
 # - ingress.yaml