secretGenerator:
  - name: mongo-db-uri
    literals:
    - database=kube_db
    - uri=mongodb://kube-app-mongo/kube_db
resources:
  - mongo-deployment.yaml
  - kube-server-deployment.yaml
  - kube-client-deployment.yaml  
  - ingress.yaml