secretGenerator:
  - name: mongo-db-secret
    literals:
    - database=kube_db
    - rootuser=root
    - rootpassword=passwort
    - user=usertest
    - password=pwdtest
resources:
  - mongo-deployment.yaml
  - kube-server-deployment.yaml
  - kube-client-deployment.yaml  
  - ingress.yaml