version: '3.7'

services:

  app-server:
    build:
      context: kube-server 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on: 
      - db
    environment:
      - MONGO_URI=mongodb://db/kube_db
    networks: 
      - backend
      - frontend

  app-client:
    build:
      context: kube-app 
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

  db:
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - backend  
  
volumes:
  db-data:

networks:
  backend:
  frontend:  